apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "users-api.fullname" . }}-config
  labels:
    {{- include "users-api.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  PORT: {{ .Values.config.PORT | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  READ_TIMEOUT: {{ .Values.config.READ_TIMEOUT | quote }}
  WRITE_TIMEOUT: {{ .Values.config.WRITE_TIMEOUT | quote }}
  IDLE_TIMEOUT: {{ .Values.config.IDLE_TIMEOUT | quote }}
  REQUEST_TIMEOUT: {{ .Values.config.REQUEST_TIMEOUT | quote }}
