apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: users-api
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cloud-native-kubernetes-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
