apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: users-api
  labels:
    app.kubernetes.io/part-of: cloud-native-kubernetes-platform
type: Opaque
stringData:
  POSTGRES_USER: "users_api"
  POSTGRES_PASSWORD: "CHANGE_ME"
  POSTGRES_DB: "users_api"
  DB_URL: "postgres://users_api:CHANGE_ME@postgres:5432/users_api?sslmode=disable"
