replicaCount: 2

config:
  APP_ENV: staging
  LOG_LEVEL: info

ingress:
  host: users-api.staging.local

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
