apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-api-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: users-api
    app.kubernetes.io/part-of: cloud-native-kubernetes-platform
    environment: dev
spec:
  project: default

  source:
    repoURL: https://github.com/dayanarojasdrp/cloud-native-kubernetes-platform.git
    targetRevision: main
    path: helm/users-api
    helm:
      releaseName: users-api-dev
      values: |
        fullnameOverride: users-api-dev

        replicaCount: 1

        config:
          APP_ENV: development
          LOG_LEVEL: debug

        ingress:
          host: users-api.dev.local
          tls:
            secretName: users-api-tls

        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
          targetCPUUtilizationPercentage: 70

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: users-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
